/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.analysis;

import compiler.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAVarsProgram(AVarsProgram node);
    void caseAVarStartCharVariable(AVarStartCharVariable node);
    void caseAVarStartCharsVars(AVarStartCharsVars node);
    void caseAVarNumVars(AVarNumVars node);
    void caseAVarCharsVars(AVarCharsVars node);
    void caseALoopVarsVars(ALoopVarsVars node);

    void caseTWhiteSpace(TWhiteSpace node);
    void caseTLpar(TLpar node);
    void caseTRpar(TRpar node);
    void caseTChars(TChars node);
    void caseTNum(TNum node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTInt(TInt node);
    void caseTThen(TThen node);
    void caseTChar(TChar node);
    void caseTMod(TMod node);
    void caseTVar(TVar node);
    void caseTDiv(TDiv node);
    void caseTNot(TNot node);
    void caseTWhile(TWhile node);
    void caseTDo(TDo node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTFun(TFun node);
    void caseTRetrun(TRetrun node);
    void caseTRef(TRef node);
    void caseTNothing(TNothing node);
    void caseEOF(EOF node);
}
