/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.analysis;

import compiler.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAOneProgram(AOneProgram node);

    void caseTWhiteSpace(TWhiteSpace node);
    void caseTComment(TComment node);
    void caseTColon(TColon node);
    void caseTSemicolon(TSemicolon node);
    void caseTComma(TComma node);
    void caseTKwAnd(TKwAnd node);
    void caseTKwOr(TKwOr node);
    void caseTKwInt(TKwInt node);
    void caseTKwThen(TKwThen node);
    void caseTKwChar(TKwChar node);
    void caseTKwMod(TKwMod node);
    void caseTKwVar(TKwVar node);
    void caseTKwDiv(TKwDiv node);
    void caseTKwNot(TKwNot node);
    void caseTKwWhile(TKwWhile node);
    void caseTKwDo(TKwDo node);
    void caseTKwIf(TKwIf node);
    void caseTKwElse(TKwElse node);
    void caseTKwFun(TKwFun node);
    void caseTKwReturn(TKwReturn node);
    void caseTKwRef(TKwRef node);
    void caseTKwNothing(TKwNothing node);
    void caseTIdentifier(TIdentifier node);
    void caseTInteger(TInteger node);
    void caseTArrayDeclaration(TArrayDeclaration node);
    void caseEOF(EOF node);
}
