/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.analysis;

import java.util.*;
import compiler.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgram().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAOneProgram(AOneProgram node)
    {
        defaultIn(node);
    }

    public void outAOneProgram(AOneProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOneProgram(AOneProgram node)
    {
        inAOneProgram(node);
        {
            List<PVariableDefinition> copy = new ArrayList<PVariableDefinition>(node.getVariableDefinition());
            for(PVariableDefinition e : copy)
            {
                e.apply(this);
            }
        }
        outAOneProgram(node);
    }

    public void inADefVariableDefinition(ADefVariableDefinition node)
    {
        defaultIn(node);
    }

    public void outADefVariableDefinition(ADefVariableDefinition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefVariableDefinition(ADefVariableDefinition node)
    {
        inADefVariableDefinition(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getSetOfVariables() != null)
        {
            node.getSetOfVariables().apply(this);
        }
        if(node.getDeftype() != null)
        {
            node.getDeftype().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getCmdEnd() != null)
        {
            node.getCmdEnd().apply(this);
        }
        outADefVariableDefinition(node);
    }

    public void inAMultiSetSetOfVariables(AMultiSetSetOfVariables node)
    {
        defaultIn(node);
    }

    public void outAMultiSetSetOfVariables(AMultiSetSetOfVariables node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiSetSetOfVariables(AMultiSetSetOfVariables node)
    {
        inAMultiSetSetOfVariables(node);
        if(node.getVariable() != null)
        {
            node.getVariable().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getSetOfVariables() != null)
        {
            node.getSetOfVariables().apply(this);
        }
        outAMultiSetSetOfVariables(node);
    }

    public void inASingleSetSetOfVariables(ASingleSetSetOfVariables node)
    {
        defaultIn(node);
    }

    public void outASingleSetSetOfVariables(ASingleSetSetOfVariables node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleSetSetOfVariables(ASingleSetSetOfVariables node)
    {
        inASingleSetSetOfVariables(node);
        if(node.getVariable() != null)
        {
            node.getVariable().apply(this);
        }
        outASingleSetSetOfVariables(node);
    }

    public void inASimpleType(ASimpleType node)
    {
        defaultIn(node);
    }

    public void outASimpleType(ASimpleType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimpleType(ASimpleType node)
    {
        inASimpleType(node);
        if(node.getDataType() != null)
        {
            node.getDataType().apply(this);
        }
        outASimpleType(node);
    }

    public void inAArrayType(AArrayType node)
    {
        defaultIn(node);
    }

    public void outAArrayType(AArrayType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayType(AArrayType node)
    {
        inAArrayType(node);
        if(node.getDataType() != null)
        {
            node.getDataType().apply(this);
        }
        if(node.getArrayDeclaration() != null)
        {
            node.getArrayDeclaration().apply(this);
        }
        outAArrayType(node);
    }

    public void inATIntDataType(ATIntDataType node)
    {
        defaultIn(node);
    }

    public void outATIntDataType(ATIntDataType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATIntDataType(ATIntDataType node)
    {
        inATIntDataType(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outATIntDataType(node);
    }

    public void inATCharDataType(ATCharDataType node)
    {
        defaultIn(node);
    }

    public void outATCharDataType(ATCharDataType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATCharDataType(ATCharDataType node)
    {
        inATCharDataType(node);
        if(node.getChar() != null)
        {
            node.getChar().apply(this);
        }
        outATCharDataType(node);
    }
}
