/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AArrayType extends PType
{
    private PDataType _dataType_;
    private TArrayDeclaration _arrayDeclaration_;

    public AArrayType()
    {
        // Constructor
    }

    public AArrayType(
        @SuppressWarnings("hiding") PDataType _dataType_,
        @SuppressWarnings("hiding") TArrayDeclaration _arrayDeclaration_)
    {
        // Constructor
        setDataType(_dataType_);

        setArrayDeclaration(_arrayDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AArrayType(
            cloneNode(this._dataType_),
            cloneNode(this._arrayDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayType(this);
    }

    public PDataType getDataType()
    {
        return this._dataType_;
    }

    public void setDataType(PDataType node)
    {
        if(this._dataType_ != null)
        {
            this._dataType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataType_ = node;
    }

    public TArrayDeclaration getArrayDeclaration()
    {
        return this._arrayDeclaration_;
    }

    public void setArrayDeclaration(TArrayDeclaration node)
    {
        if(this._arrayDeclaration_ != null)
        {
            this._arrayDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataType_)
            + toString(this._arrayDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataType_ == child)
        {
            this._dataType_ = null;
            return;
        }

        if(this._arrayDeclaration_ == child)
        {
            this._arrayDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataType_ == oldChild)
        {
            setDataType((PDataType) newChild);
            return;
        }

        if(this._arrayDeclaration_ == oldChild)
        {
            setArrayDeclaration((TArrayDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
