/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ACond3Cond2 extends PCond2
{
    private PCond3 _cond3_;

    public ACond3Cond2()
    {
        // Constructor
    }

    public ACond3Cond2(
        @SuppressWarnings("hiding") PCond3 _cond3_)
    {
        // Constructor
        setCond3(_cond3_);

    }

    @Override
    public Object clone()
    {
        return new ACond3Cond2(
            cloneNode(this._cond3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACond3Cond2(this);
    }

    public PCond3 getCond3()
    {
        return this._cond3_;
    }

    public void setCond3(PCond3 node)
    {
        if(this._cond3_ != null)
        {
            this._cond3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond3_ == child)
        {
            this._cond3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond3_ == oldChild)
        {
            setCond3((PCond3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
