/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ACond1Cond extends PCond
{
    private PCond1 _cond1_;

    public ACond1Cond()
    {
        // Constructor
    }

    public ACond1Cond(
        @SuppressWarnings("hiding") PCond1 _cond1_)
    {
        // Constructor
        setCond1(_cond1_);

    }

    @Override
    public Object clone()
    {
        return new ACond1Cond(
            cloneNode(this._cond1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACond1Cond(this);
    }

    public PCond1 getCond1()
    {
        return this._cond1_;
    }

    public void setCond1(PCond1 node)
    {
        if(this._cond1_ != null)
        {
            this._cond1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond1_ == child)
        {
            this._cond1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond1_ == oldChild)
        {
            setCond1((PCond1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
