/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AExistingArrayDec extends PArrayDec
{
    private final LinkedList<TIntConst> _intConst_ = new LinkedList<TIntConst>();

    public AExistingArrayDec()
    {
        // Constructor
    }

    public AExistingArrayDec(
        @SuppressWarnings("hiding") List<?> _intConst_)
    {
        // Constructor
        setIntConst(_intConst_);

    }

    @Override
    public Object clone()
    {
        return new AExistingArrayDec(
            cloneList(this._intConst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExistingArrayDec(this);
    }

    public LinkedList<TIntConst> getIntConst()
    {
        return this._intConst_;
    }

    public void setIntConst(List<?> list)
    {
        for(TIntConst e : this._intConst_)
        {
            e.parent(null);
        }
        this._intConst_.clear();

        for(Object obj_e : list)
        {
            TIntConst e = (TIntConst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._intConst_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intConst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intConst_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TIntConst> i = this._intConst_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIntConst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
