/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncDef extends PFuncDef
{
    private TId _id_;
    private PFparList _vars_;
    private PType _retType_;
    private PLocalDefList _localDefs_;

    public AFuncDef()
    {
        // Constructor
    }

    public AFuncDef(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PFparList _vars_,
        @SuppressWarnings("hiding") PType _retType_,
        @SuppressWarnings("hiding") PLocalDefList _localDefs_)
    {
        // Constructor
        setId(_id_);

        setVars(_vars_);

        setRetType(_retType_);

        setLocalDefs(_localDefs_);

    }

    @Override
    public Object clone()
    {
        return new AFuncDef(
            cloneNode(this._id_),
            cloneNode(this._vars_),
            cloneNode(this._retType_),
            cloneNode(this._localDefs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDef(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PFparList getVars()
    {
        return this._vars_;
    }

    public void setVars(PFparList node)
    {
        if(this._vars_ != null)
        {
            this._vars_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vars_ = node;
    }

    public PType getRetType()
    {
        return this._retType_;
    }

    public void setRetType(PType node)
    {
        if(this._retType_ != null)
        {
            this._retType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._retType_ = node;
    }

    public PLocalDefList getLocalDefs()
    {
        return this._localDefs_;
    }

    public void setLocalDefs(PLocalDefList node)
    {
        if(this._localDefs_ != null)
        {
            this._localDefs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._localDefs_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._vars_)
            + toString(this._retType_)
            + toString(this._localDefs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._vars_ == child)
        {
            this._vars_ = null;
            return;
        }

        if(this._retType_ == child)
        {
            this._retType_ = null;
            return;
        }

        if(this._localDefs_ == child)
        {
            this._localDefs_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._vars_ == oldChild)
        {
            setVars((PFparList) newChild);
            return;
        }

        if(this._retType_ == oldChild)
        {
            setRetType((PType) newChild);
            return;
        }

        if(this._localDefs_ == oldChild)
        {
            setLocalDefs((PLocalDefList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
