/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncDecLocalDef extends PLocalDef
{
    private PFuncDec _funcDec_;

    public AFuncDecLocalDef()
    {
        // Constructor
    }

    public AFuncDecLocalDef(
        @SuppressWarnings("hiding") PFuncDec _funcDec_)
    {
        // Constructor
        setFuncDec(_funcDec_);

    }

    @Override
    public Object clone()
    {
        return new AFuncDecLocalDef(
            cloneNode(this._funcDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDecLocalDef(this);
    }

    public PFuncDec getFuncDec()
    {
        return this._funcDec_;
    }

    public void setFuncDec(PFuncDec node)
    {
        if(this._funcDec_ != null)
        {
            this._funcDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcDec_ == child)
        {
            this._funcDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcDec_ == oldChild)
        {
            setFuncDec((PFuncDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
