/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AIfMatched extends PMatched
{
    private PMatchedIf _matchedIf_;

    public AIfMatched()
    {
        // Constructor
    }

    public AIfMatched(
        @SuppressWarnings("hiding") PMatchedIf _matchedIf_)
    {
        // Constructor
        setMatchedIf(_matchedIf_);

    }

    @Override
    public Object clone()
    {
        return new AIfMatched(
            cloneNode(this._matchedIf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfMatched(this);
    }

    public PMatchedIf getMatchedIf()
    {
        return this._matchedIf_;
    }

    public void setMatchedIf(PMatchedIf node)
    {
        if(this._matchedIf_ != null)
        {
            this._matchedIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matchedIf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._matchedIf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._matchedIf_ == child)
        {
            this._matchedIf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._matchedIf_ == oldChild)
        {
            setMatchedIf((PMatchedIf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
