/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ALoopVarsVars extends PVars
{
    private PVars _vars_;

    public ALoopVarsVars()
    {
        // Constructor
    }

    public ALoopVarsVars(
        @SuppressWarnings("hiding") PVars _vars_)
    {
        // Constructor
        setVars(_vars_);

    }

    @Override
    public Object clone()
    {
        return new ALoopVarsVars(
            cloneNode(this._vars_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoopVarsVars(this);
    }

    public PVars getVars()
    {
        return this._vars_;
    }

    public void setVars(PVars node)
    {
        if(this._vars_ != null)
        {
            this._vars_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vars_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vars_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vars_ == child)
        {
            this._vars_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vars_ == oldChild)
        {
            setVars((PVars) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
