/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AMultiExprList extends PExprList
{
    private PExpr _expr_;
    private final LinkedList<PExprListTail> _exprListTail_ = new LinkedList<PExprListTail>();

    public AMultiExprList()
    {
        // Constructor
    }

    public AMultiExprList(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") List<?> _exprListTail_)
    {
        // Constructor
        setExpr(_expr_);

        setExprListTail(_exprListTail_);

    }

    @Override
    public Object clone()
    {
        return new AMultiExprList(
            cloneNode(this._expr_),
            cloneList(this._exprListTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiExprList(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public LinkedList<PExprListTail> getExprListTail()
    {
        return this._exprListTail_;
    }

    public void setExprListTail(List<?> list)
    {
        for(PExprListTail e : this._exprListTail_)
        {
            e.parent(null);
        }
        this._exprListTail_.clear();

        for(Object obj_e : list)
        {
            PExprListTail e = (PExprListTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._exprListTail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._exprListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._exprListTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        for(ListIterator<PExprListTail> i = this._exprListTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExprListTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
