/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ANamesNamepart extends PNamepart
{
    private TLetter _letter_;
    private PNamepart _namepart_;

    public ANamesNamepart()
    {
        // Constructor
    }

    public ANamesNamepart(
        @SuppressWarnings("hiding") TLetter _letter_,
        @SuppressWarnings("hiding") PNamepart _namepart_)
    {
        // Constructor
        setLetter(_letter_);

        setNamepart(_namepart_);

    }

    @Override
    public Object clone()
    {
        return new ANamesNamepart(
            cloneNode(this._letter_),
            cloneNode(this._namepart_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANamesNamepart(this);
    }

    public TLetter getLetter()
    {
        return this._letter_;
    }

    public void setLetter(TLetter node)
    {
        if(this._letter_ != null)
        {
            this._letter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._letter_ = node;
    }

    public PNamepart getNamepart()
    {
        return this._namepart_;
    }

    public void setNamepart(PNamepart node)
    {
        if(this._namepart_ != null)
        {
            this._namepart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._namepart_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._letter_)
            + toString(this._namepart_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._letter_ == child)
        {
            this._letter_ = null;
            return;
        }

        if(this._namepart_ == child)
        {
            this._namepart_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._letter_ == oldChild)
        {
            setLetter((TLetter) newChild);
            return;
        }

        if(this._namepart_ == oldChild)
        {
            setNamepart((PNamepart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
