/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ANothDataType extends PDataType
{
    private TKwNothing _kwNothing_;

    public ANothDataType()
    {
        // Constructor
    }

    public ANothDataType(
        @SuppressWarnings("hiding") TKwNothing _kwNothing_)
    {
        // Constructor
        setKwNothing(_kwNothing_);

    }

    @Override
    public Object clone()
    {
        return new ANothDataType(
            cloneNode(this._kwNothing_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANothDataType(this);
    }

    public TKwNothing getKwNothing()
    {
        return this._kwNothing_;
    }

    public void setKwNothing(TKwNothing node)
    {
        if(this._kwNothing_ != null)
        {
            this._kwNothing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwNothing_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwNothing_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwNothing_ == child)
        {
            this._kwNothing_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwNothing_ == oldChild)
        {
            setKwNothing((TKwNothing) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
