/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AOneProgram extends PProgram
{
    private final LinkedList<PVariableDefinition> _variableDefinition_ = new LinkedList<PVariableDefinition>();

    public AOneProgram()
    {
        // Constructor
    }

    public AOneProgram(
        @SuppressWarnings("hiding") List<?> _variableDefinition_)
    {
        // Constructor
        setVariableDefinition(_variableDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AOneProgram(
            cloneList(this._variableDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneProgram(this);
    }

    public LinkedList<PVariableDefinition> getVariableDefinition()
    {
        return this._variableDefinition_;
    }

    public void setVariableDefinition(List<?> list)
    {
        for(PVariableDefinition e : this._variableDefinition_)
        {
            e.parent(null);
        }
        this._variableDefinition_.clear();

        for(Object obj_e : list)
        {
            PVariableDefinition e = (PVariableDefinition) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._variableDefinition_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variableDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variableDefinition_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PVariableDefinition> i = this._variableDefinition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVariableDefinition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
