/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AOrCond extends PCond
{
    private PCond _cond_;
    private TKwOr _kwOr_;
    private PCond1 _cond1_;

    public AOrCond()
    {
        // Constructor
    }

    public AOrCond(
        @SuppressWarnings("hiding") PCond _cond_,
        @SuppressWarnings("hiding") TKwOr _kwOr_,
        @SuppressWarnings("hiding") PCond1 _cond1_)
    {
        // Constructor
        setCond(_cond_);

        setKwOr(_kwOr_);

        setCond1(_cond1_);

    }

    @Override
    public Object clone()
    {
        return new AOrCond(
            cloneNode(this._cond_),
            cloneNode(this._kwOr_),
            cloneNode(this._cond1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrCond(this);
    }

    public PCond getCond()
    {
        return this._cond_;
    }

    public void setCond(PCond node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public TKwOr getKwOr()
    {
        return this._kwOr_;
    }

    public void setKwOr(TKwOr node)
    {
        if(this._kwOr_ != null)
        {
            this._kwOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwOr_ = node;
    }

    public PCond1 getCond1()
    {
        return this._cond1_;
    }

    public void setCond1(PCond1 node)
    {
        if(this._cond1_ != null)
        {
            this._cond1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond_)
            + toString(this._kwOr_)
            + toString(this._cond1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._kwOr_ == child)
        {
            this._kwOr_ = null;
            return;
        }

        if(this._cond1_ == child)
        {
            this._cond1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond_ == oldChild)
        {
            setCond((PCond) newChild);
            return;
        }

        if(this._kwOr_ == oldChild)
        {
            setKwOr((TKwOr) newChild);
            return;
        }

        if(this._cond1_ == oldChild)
        {
            setCond1((PCond1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
