/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class ASFactorTerm extends PTerm
{
    private PSignedFactor _signedFactor_;

    public ASFactorTerm()
    {
        // Constructor
    }

    public ASFactorTerm(
        @SuppressWarnings("hiding") PSignedFactor _signedFactor_)
    {
        // Constructor
        setSignedFactor(_signedFactor_);

    }

    @Override
    public Object clone()
    {
        return new ASFactorTerm(
            cloneNode(this._signedFactor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASFactorTerm(this);
    }

    public PSignedFactor getSignedFactor()
    {
        return this._signedFactor_;
    }

    public void setSignedFactor(PSignedFactor node)
    {
        if(this._signedFactor_ != null)
        {
            this._signedFactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._signedFactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._signedFactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._signedFactor_ == child)
        {
            this._signedFactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._signedFactor_ == oldChild)
        {
            setSignedFactor((PSignedFactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
