/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AType extends PType
{
    private PDataType _dataType_;
    private PArrayDec _arrayDec_;

    public AType()
    {
        // Constructor
    }

    public AType(
        @SuppressWarnings("hiding") PDataType _dataType_,
        @SuppressWarnings("hiding") PArrayDec _arrayDec_)
    {
        // Constructor
        setDataType(_dataType_);

        setArrayDec(_arrayDec_);

    }

    @Override
    public Object clone()
    {
        return new AType(
            cloneNode(this._dataType_),
            cloneNode(this._arrayDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAType(this);
    }

    public PDataType getDataType()
    {
        return this._dataType_;
    }

    public void setDataType(PDataType node)
    {
        if(this._dataType_ != null)
        {
            this._dataType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataType_ = node;
    }

    public PArrayDec getArrayDec()
    {
        return this._arrayDec_;
    }

    public void setArrayDec(PArrayDec node)
    {
        if(this._arrayDec_ != null)
        {
            this._arrayDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataType_)
            + toString(this._arrayDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataType_ == child)
        {
            this._dataType_ = null;
            return;
        }

        if(this._arrayDec_ == child)
        {
            this._arrayDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataType_ == oldChild)
        {
            setDataType((PDataType) newChild);
            return;
        }

        if(this._arrayDec_ == oldChild)
        {
            setArrayDec((PArrayDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
