/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import java.util.*;
import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AVarStartCharsVars extends PVars
{
    private final LinkedList<TChars> _chars_ = new LinkedList<TChars>();

    public AVarStartCharsVars()
    {
        // Constructor
    }

    public AVarStartCharsVars(
        @SuppressWarnings("hiding") List<?> _chars_)
    {
        // Constructor
        setChars(_chars_);

    }

    @Override
    public Object clone()
    {
        return new AVarStartCharsVars(
            cloneList(this._chars_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarStartCharsVars(this);
    }

    public LinkedList<TChars> getChars()
    {
        return this._chars_;
    }

    public void setChars(List<?> list)
    {
        for(TChars e : this._chars_)
        {
            e.parent(null);
        }
        this._chars_.clear();

        for(Object obj_e : list)
        {
            TChars e = (TChars) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._chars_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chars_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chars_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TChars> i = this._chars_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TChars) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
