/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AVarCharsVariable extends PVariable
{
    private TChars _chars_;

    public AVarCharsVariable()
    {
        // Constructor
    }

    public AVarCharsVariable(
        @SuppressWarnings("hiding") TChars _chars_)
    {
        // Constructor
        setChars(_chars_);

    }

    @Override
    public Object clone()
    {
        return new AVarCharsVariable(
            cloneNode(this._chars_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarCharsVariable(this);
    }

    public TChars getChars()
    {
        return this._chars_;
    }

    public void setChars(TChars node)
    {
        if(this._chars_ != null)
        {
            this._chars_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chars_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chars_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chars_ == child)
        {
            this._chars_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chars_ == oldChild)
        {
            setChars((TChars) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
