/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AVarStartCharVariable extends PVariable
{
    private TVar _var_;
    private PVars _vars_;

    public AVarStartCharVariable()
    {
        // Constructor
    }

    public AVarStartCharVariable(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") PVars _vars_)
    {
        // Constructor
        setVar(_var_);

        setVars(_vars_);

    }

    @Override
    public Object clone()
    {
        return new AVarStartCharVariable(
            cloneNode(this._var_),
            cloneNode(this._vars_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarStartCharVariable(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PVars getVars()
    {
        return this._vars_;
    }

    public void setVars(PVars node)
    {
        if(this._vars_ != null)
        {
            this._vars_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vars_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._vars_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._vars_ == child)
        {
            this._vars_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._vars_ == oldChild)
        {
            setVars((PVars) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
