/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AVariablesVariable extends PVariable
{
    private TVar _var_;
    private PNamepart _namepart_;

    public AVariablesVariable()
    {
        // Constructor
    }

    public AVariablesVariable(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") PNamepart _namepart_)
    {
        // Constructor
        setVar(_var_);

        setNamepart(_namepart_);

    }

    @Override
    public Object clone()
    {
        return new AVariablesVariable(
            cloneNode(this._var_),
            cloneNode(this._namepart_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariablesVariable(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PNamepart getNamepart()
    {
        return this._namepart_;
    }

    public void setNamepart(PNamepart node)
    {
        if(this._namepart_ != null)
        {
            this._namepart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._namepart_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._namepart_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._namepart_ == child)
        {
            this._namepart_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._namepart_ == oldChild)
        {
            setNamepart((PNamepart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
