/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class AWhileUnmatched extends PUnmatched
{
    private PUnmatchedWhile _unmatchedWhile_;

    public AWhileUnmatched()
    {
        // Constructor
    }

    public AWhileUnmatched(
        @SuppressWarnings("hiding") PUnmatchedWhile _unmatchedWhile_)
    {
        // Constructor
        setUnmatchedWhile(_unmatchedWhile_);

    }

    @Override
    public Object clone()
    {
        return new AWhileUnmatched(
            cloneNode(this._unmatchedWhile_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileUnmatched(this);
    }

    public PUnmatchedWhile getUnmatchedWhile()
    {
        return this._unmatchedWhile_;
    }

    public void setUnmatchedWhile(PUnmatchedWhile node)
    {
        if(this._unmatchedWhile_ != null)
        {
            this._unmatchedWhile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unmatchedWhile_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unmatchedWhile_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unmatchedWhile_ == child)
        {
            this._unmatchedWhile_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unmatchedWhile_ == oldChild)
        {
            setUnmatchedWhile((PUnmatchedWhile) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
