/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class TArrayDeclaration extends Token
{
    public TArrayDeclaration(String text)
    {
        setText(text);
    }

    public TArrayDeclaration(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArrayDeclaration(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArrayDeclaration(this);
    }
}
