/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiler.node;

import compiler.analysis.*;

@SuppressWarnings("nls")
public final class TKwDiv extends Token
{
    public TKwDiv()
    {
        super.setText("div");
    }

    public TKwDiv(int line, int pos)
    {
        super.setText("div");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwDiv(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwDiv(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwDiv text.");
    }
}
